# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_circulos_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='circulos_m',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
